#Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
#1, 2, 3, 5, 8, 13, 21, 34, 55, 89...
#By considering the terms in this sequnce that do no exceed 4 million, find the sum of the even-valued terms.


num1 = 1
num2 = 2

def fibonacci_finder(num1, num2):
    total = 0
    while num1 < 4000000:
        temp = num1 + num2
        if num2 % 2 == 0:
            total += num2
        num1 = num2
        num2 = temp
        
    return total

print(fibonacci_finder(num1, num2))
